version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3 # primary container
    steps:
      - checkout

  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - run: python todo_server.py
      - run: curl http://localhost:8080


workflows:
  version: 2
  todo_server_checker:
    jobs:
      - build
      - test:
          requires:
            - build