version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3 # primary container
    steps:
      - checkout

  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: 
          name: サーバー起動
          command: python todo_server.py
          background: true
      - run: 
          name: サーバー起動待ち(5秒間)
          command: sleep 5
      - run: 
          name: TODOが一件もない時、全取得　→　Not Found(正常)
          command: curl -X GET http://localhost:8080/api/v1/event
      - run: 
          name: TODO登録　→　登録成功(正常)
          command: curl -X POST -H "Content-Type:application/json" -d '{"deadline":"2019-06-11T14:00:00+09:00", "title":"レポート提出", "memo":""}' http://localhost:8080/api/v1/event
      - run: 
          name: TODOが一件、全取得(正常)
          command: curl -X GET http://localhost:8080/api/v1/event
      - run: 
          name: TODOが一件、存在するID指定取得(正常)
          command: curl -X GET http://localhost:8080/api/v1/event/1
      - run: 
          name: TODOが一件、存在しないID指定取得(異常)
          command: curl -X GET http://localhost:8080/api/v1/event/5

workflows:
  version: 2
  todo_server_checker:
    jobs:
      - build
      - test:
          requires:
            - build