version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3 # primary container
    steps:
      - checkout

  test:
    machine: true
    steps:
      - checkout
      - run:
        command: |
          echo "OK!"

workflows:
  version: 2
  todo_server_checker:
    jobs:
      - build
      - test:
          requires:
            - build